eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        # defaultZone: http://docker.host.internal:8761/eureka
        defaultZone: ${EUREKA_SERVER_ADDRESS:http}
